# site settings
title: EaaS
subtitle: engineer as a service
email: viktor.manuel.garcia@gmail.com
description: We are going to work closely with your team to build a scalable solution in the shortest possible time using the latest technologies in the market.
baseurl: # the subpath of your site, e.g. /blog
url: https://eaas.solutions # the base hostname & protocol for your site
author:
street_address:
city: Barcelona
zip_code:
country: Spain
phone: (+34) 672104297

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# contact form settings
form_url: https://formspree.io/viktor.manuel.garcia@gmail.com # endpoint URL to receive contact form submissions
form_email_name: _replyto # value of the "name" attribute in the "email" field

# social settings
500px_url:
facebook_url:
github_url: https://github.com/vgmartinez
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/victor-manuel-garcia-martinez-77706582/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/g_vmanuel

# build settings
markdown: kramdown

sass:
  style: compressed

plugins:
- jekyll-analytics

jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-122663797-1          # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking